plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-teaching-cs.github.io 
baseurl: "/"  

course: "CS 190J"
course_title: "UCSB Teaching CS"


title: "UCSB Teaching CS"
course_num: "CS190J"
github_url: https://github.com/ucsb-teaching-cs/ucsb-teaching-cs.github.io
gauchospace_url: TBD
piazza_url: TBD

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048/

#kramdown:
#  parse_block_html: true

include:
  - _pages
exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:

  topics:
    output: true
    permalink: /topics/:path/

  resources:
    output: true
    permalink: /resources/:path/
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: ""
      type: topics
    values:
      layout: default
  - scope:
      path: ""
      type: resources
    values:
      layout: default
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: "default"

